jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          command: |
            npm install
            npm run build
      - run:
          command: |
            export APPLITOOLS_BATCH_ID=`git rev-parse HEAD`
            echo $APPLITOOLS_BATCH_ID
            npm test
